// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxUGmubd40_WSKqNNotE7B3mJyxb6otw',
    appId: '1:208533265645:web:d5fc4683381428341000e4',
    messagingSenderId: '208533265645',
    projectId: 'miniproject-10a97',
    authDomain: 'miniproject-10a97.firebaseapp.com',
    storageBucket: 'miniproject-10a97.appspot.com',
    measurementId: 'G-3JQK1BJTYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6v4kZSgCT7mf38TvJejgeI8Ygs38VDOw',
    appId: '1:208533265645:android:c2c367aeedd64bc61000e4',
    messagingSenderId: '208533265645',
    projectId: 'miniproject-10a97',
    storageBucket: 'miniproject-10a97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSdpatPm_R6-vA0w8xlBcnZw8YvGzJljE',
    appId: '1:208533265645:ios:41aad95ef8eb82641000e4',
    messagingSenderId: '208533265645',
    projectId: 'miniproject-10a97',
    storageBucket: 'miniproject-10a97.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSdpatPm_R6-vA0w8xlBcnZw8YvGzJljE',
    appId: '1:208533265645:ios:41aad95ef8eb82641000e4',
    messagingSenderId: '208533265645',
    projectId: 'miniproject-10a97',
    storageBucket: 'miniproject-10a97.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKxUGmubd40_WSKqNNotE7B3mJyxb6otw',
    appId: '1:208533265645:web:c759c6f3926b2c441000e4',
    messagingSenderId: '208533265645',
    projectId: 'miniproject-10a97',
    authDomain: 'miniproject-10a97.firebaseapp.com',
    storageBucket: 'miniproject-10a97.appspot.com',
    measurementId: 'G-K9K4JFVDHJ',
  );
}
